### ISSUE TITLE
Bookable product imported as simple product

### ISSUE THREAD

**Issue by kosiew** [woocommerce/bookings-helper#16]
The  zip file is imported as simple products instead of Bookable products.

1. Exported from my test site booking-product-4018-2020-10-28.zip

[booking-product-4018-2020-10-28.zip](https://github.com/woocommerce/bookings-helper/files/5449253/booking-product-4018-2020-10-28.zip)

From test site:
![Screenshot](https://d.pr/i/M3q002+)
*if image does not load, please click on this link  : https://d.pr/i/M3q002*

After import to another site:
![Screenshot](https://d.pr/i/NE7vSW+)
*if image does not load, please click on this link  : https://d.pr/i/NE7vSW*

**Comment by roykho** [comment]
Hi there - make sure the site you're importing it to has Bookings active. I just tested the zip file you linked and imported with no issues. ![](https://d.pr/i/7IhfVG+)

**Comment by kosiew** [comment]
Hi Roy, 

Thanks for checking.

Bookings is active.

Here is the SSR

`
### WordPress Environment ###

WordPress address (URL): https://wpstore102.mystagingwebsite.com
Site address (URL): https://wpstore102.mystagingwebsite.com
WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.23
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.72.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: wp_
Total Database Size: 5.69MB
Database Data Size: 2.72MB
Database Index Size: 2.97MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.27MB + Index: 0.56MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.14MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 36
bookable_resource: 5
custom_css: 1
customize_changeset: 6
global_product_addon: 1
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
page: 8
post: 1
product: 27
product_variation: 14
revision: 15
shop_coupon: 1
shop_order: 7
shop_subscription: 1
wc_booking: 2
wc_membership_plan: 1
wc_user_membership: 1
wp_template: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.6.1
Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce Bookings: by WooCommerce – 1.15.29 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce: by Automattic – 4.6.1

### Inactive Plugins (45) ###

Akismet Anti-Spam: by Automattic – 4.1.7
All-in-One WP Migration: by ServMask – 7.26
AutomateWoo: by WooCommerce – 5.0.1 – Installed version not tested with active version of WooCommerce 4.6.1
Code Snippets: by Code Snippets Pro – 2.14.0
Disable Real MIME Check: by Sergey Biryukov – 1.0
Facebook for WooCommerce: by Facebook – 2.0.1 – Installed version not tested with active version of WooCommerce 4.6.1
Free Gifts for WooCommerce: by FantasticPlugins – 5.4 – Installed version not tested with active version of WooCommerce 4.6.1
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.6.1
Groups: by itthinx – 2.10.0
Gutenberg: by Gutenberg Team – 9.2.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack by WordPress.com: by Automattic – 9.0.2
Mailchimp for WooCommerce: by Mailchimp – 2.4.5 – Installed version not tested with active version of WooCommerce 4.6.1
Media Cleaner: by Jordy Meow – 6.0.4
Query Monitor: by John Blackbourn – 3.6.4
Sensei LMS: by Automattic – 3.5.0 (update to version 3.5.2 is available)
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.26

User Role Editor: by Vladimir Garagulya – 4.56
WooCommerce Blocks: by Automattic – 3.2 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Cart Add-Ons: by WooCommerce – 1.15.32 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Chained Products: by StoreApps – 2.9.6 (update to version 2.9.8 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.36 (update to version 1.5.37 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Composite Products: by SomewhereWarm – 7.0.5 (update to version 7.1.1 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Currency Converter: by WooCommerce – 1.6.22 (update to version 1.6.23 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Deposits: by WooCommerce – 1.5.2 (update to version 1.5.5 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.21 (update to version 3.1.22 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Force Sells: by WooCommerce – 1.1.24 (update to version 1.1.27 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Memberships: by SkyVerge – 1.18.0 (update to version 1.19.2 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Mix and Match Products: by Kathy Darling – 1.10.0 (update to version 1.10.4 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Payments: by Automattic – 1.3.0 (update to version 1.6.0 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce PDF Product Vouchers: by SkyVerge – 3.8.0 (update to version 3.8.1 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.36 (update to version 3.1.0 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.3 (update to version 6.4.2 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.35 (update to version 1.10.37 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Services: by Automattic – 1.24.1 (update to version 1.25.0 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.10 (update to version 2.3.12 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Smart Coupons: by StoreApps – 4.7.8 (update to version 4.11.0 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Subscriptions: by WooCommerce – 3.0.7 (update to version 3.0.9 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.28 (update to version 3.0.30 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.27 (update to version 3.2.29 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.46 (update to version 4.4.48 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WooCommerce Xero Integration: by WooCommerce – 1.7.32 (update to version 1.7.33 is available) – Installed version not tested with active version of WooCommerce 4.6.1
WP Mail Logging: by MailPoet – 1.9.7
WP phpMyAdmin: by Puvox.software – 5.0.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 30
Oldest: 2020-09-30 01:05:28 +0000
Newest: 2020-10-28 13:23:35 +0000

Pending: 1
Oldest: 2021-08-27 09:05:35 +0000
Newest: 2021-08-27 09:05:35 +0000

`

**Comment by kosiew** [comment]
After clearing cache, the product shows as Bookable product.
