### ISSUE TITLE
Importing Global Availability Rules doesn't working

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/bookings-helper#18]
**Tools > Bookings Helper > Import Rules** does not add to the Store Availability found under **Bookings > Settings > Store Availability**:

[bookings-global-rules-2021-03-08.zip](https://github.com/woocommerce/bookings-helper/files/6103152/bookings-global-rules-2021-03-08.zip)

**Comment by faisal-alvi** [comment]
@johndcoy I have tested and the global rules are imported successfully.

![helper-18](https://user-images.githubusercontent.com/25176325/182350734-30f45e21-d1fb-4c70-9d1d-265c05c04e2c.gif)

Closing, please re-open it if it still does not work for you.
