### ISSUE TITLE
Importing a product ZIP creates a Simple product, doesn't enable resources

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/bookings-helper#19]
When importing a product it's not assigned the Bookable Product type and if Resources are enabled, the resources option is not ticked. Although, after ticking Resources, the assigned resources are listed as expected.

**Comment by faisal-alvi** [comment]
@johndcoy I have tested and tried importing a bookable product with and without resources, both worked fine and imported successfully for me.

Closing, please re-open it (with more detailed steps) if it still does not work for you.
