### ISSUE TITLE
Importing a product doesn't set the block price for persons and has persons isn't checked

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/bookings-helper#20]
When importing a product that contains persons the block price is not set.

I imported a product that has persons with the block price set:

<img width="1137" alt="Markup 2022-02-01 at 10 40 47" src="https://user-images.githubusercontent.com/40762232/151954268-f375fe53-2799-4010-90c2-1e9c70f2be2b.png">

The product is imported without `Has persons` being enabled. When that's checked, the persons data will be there but the block price is empty.

**Comment by faisal-alvi** [comment]
Hi @martynmjones, I have tested by adding 2 person types; each with a different "Block Cost". It was successfully imported with correct Block Prices. Please check this quick video:

https://user-images.githubusercontent.com/25176325/182353117-c431df1c-6dd6-4699-a6fe-d52a3e49e59b.mp4

Please share more detailed steps if it still does not work for you.

**Comment by jeffpaul** [comment]
Closing for now as we're not able to replicate this issue, but if we've misunderstood things or if additional replication steps can be shared then please re-open... thanks!
