### ISSUE TITLE
Fatal error on resources edit page and calendar loading endlessly when product imported through bookings helper

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/bookings-helper#28]
I was working on a ticket with a different issue. (5582280-zen)

I imported one of the products from user's site and checked on my test site:

1. The calendar doesn't load up (Infinite spinning)
2. Fatal error is thrown on Resource edit page.

ZIP of the product: [https://d.pr/f/KDLyCm](https://href.li/?https://d.pr/f/KDLyCm)

> 2022-09-27T04:37:10+00:00 CRITICAL Uncaught TypeError: Cannot access offset of type string on string in /var/www/site/public_html/sites/wp-3559132/wp-content/plugins/woocommerce-bookings/includes/admin/views/html-booking-availability-fields.php:43

(PHP 8.xx)

**Comment by kaushikasomaiya** [comment]
@jeffpaul Sure, 

- Bookings Helper 1.0.4
- Bookings  1.15.63

**Comment by faisal-alvi** [comment]
Update: I have applied a fix in #29. @kaushikasomaiya thanks for the report.
