### ISSUE TITLE
Add WP CLI command to export & import all booking products

### ISSUE THREAD

**Issue by ravinderk** [woocommerce/bookings-helper#32]
## Details
I expect the WP CLI command to export and import all products.

## Expectations with the WP CLI feature would be:

* Run `wp booking-helper export-product --all --dir=/absolute/path/to/directory` to export all products.
* Run`wp booking-helper import-product --file=/absolute/path/to/file/` to import all products.
* Run `wp booking-helper export-availability-rules --dir=/absolute/path/to/directory` to export global availability rules.
* Run `wp booking-helper import-availability-rules --file=/absolute/path/to/directory` to import global availability rules.

**Comment by ravinderk** [comment]
Note: This command will be useful to create booking products in bulk for E2E Tests: https://github.com/woocommerce/woocommerce-bookings/pull/3523

**Comment by faisal-alvi** [comment]
Similar #30
