### ISSUE TITLE
Ability to import/export zipped JSON

### ISSUE THREAD

**Issue by gedex** [woocommerce/bookings-helper#5]
GitHub doesn't support uploading `.json` file:

<img width="727" alt="screen shot 2017-03-28 at 11 58 18 pm" src="https://cloud.githubusercontent.com/assets/78313/24417421/833aa218-1412-11e7-873c-46a340592e17.png">

It'd be great to support zip archive when exporting.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/bookings-helper/releases/tag/1.0.2
