### ISSUE TITLE
WP CLI support

### ISSUE THREAD

**Issue by gedex** [woocommerce/bookings-helper#6]
Common flow using this helper is:

* A goes to the Helper page
* A exports by specifying product ID
* A goes to the download folder in their OS
* A makes zip archive of exported JSON file
* A uploads that in GH issue
* B downloads zip file from GH issue
* B unzips the zip
* B goes to the Helper page
* B imports JSON file

Expectation with WP CLI feature would be:

* A runs `wp booking-helper export-product 1234 --file=~/Desktop/1234.json.zip`
* A uploads `~/Desktop/1234.json.zip` in GH issue
* B copies link in GH issue and runs `wp booking-helper import-product <copied-url-from-above>`

**Comment by laurendavissmith** [comment]
Closing for now
